import React, { useEffect, useMemo, useState } from "react";
import api, { fmtINR, formatApiError } from "@/lib/api";
import { AlertTriangle, CalendarClock, CheckCircle2, Edit3, PackageSearch, Phone, Search, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";

const emptyForm = { name: "", age: "", phone: "", address: "", medicine_name: "", duration_days: "", last_refill_date: "", condition: "" };
const trimPatientForm = (patient) => Object.fromEntries(Object.keys(emptyForm).map((key) => [key, String(patient[key] || "").trim()]));
const collection = (data) => Array.isArray(data) ? data : data?.items || data?.medicines || data?.results || [];
const stockOf = (item) => Number(item?.available_stock ?? item?.available_units ?? item?.available_quantity ?? item?.quantity_units ?? item?.total_stock ?? item?.stock ?? 0);
const medicineName = (item) => item?.name || item?.medicine_name || item?.brand_name || "Unnamed medicine";
const medicineBatches = (item) => Array.isArray(item?.batches) && item.batches.length ? item.batches : [item];
const isLowStock = (item) => item?.is_low_stock === true || ["low", "low_stock", "critical", "sold_out", "out_of_stock"].includes(String(item?.stock_status || item?.inventory_status || item?.status || "").toLowerCase().replace(/ /g, "_")) || stockOf(item) <= Number(item?.low_stock_threshold ?? 0);

export default function Patients() {
  const [form, setForm] = useState(emptyForm);
  const [patients, setPatients] = useState([]);
  const [alerts, setAlerts] = useState([]);
  const [medicines, setMedicines] = useState([]);
  const [medicineSearch, setMedicineSearch] = useState("");
  const [showMedicineResults, setShowMedicineResults] = useState(false);
  const [editingPatient, setEditingPatient] = useState(null);

  const loadPatients = async () => { try { const { data } = await api.get("/patients"); setPatients(collection(data).sort((a, b) => (b.is_due === true) - (a.is_due === true))); } catch (err) { console.warn(err); } };
  const loadAlerts = async () => { try { const { data } = await api.get("/patients/alerts"); setAlerts(collection(data)); } catch (err) { console.warn(err); } };
  useEffect(() => { loadPatients(); loadAlerts(); api.get("/medicines").then(({ data }) => setMedicines(collection(data))).catch((err) => console.warn("Could not load inventory medicines", err)); }, []);

  const selectForEdit = (patient) => { setEditingPatient(patient); setForm(trimPatientForm(patient)); setMedicineSearch(patient.medicine_name || ""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const savePatient = async () => {
    const trimmedForm = trimPatientForm(form);
    if (!trimmedForm.name || !trimmedForm.phone) return toast.error("Patient name and phone are required");
    const payload = { ...trimmedForm, age: Number(trimmedForm.age), duration_days: Number(trimmedForm.duration_days) };
    try {
      if (editingPatient) { const phone = String(editingPatient.phone || "").trim(); if (!phone) return toast.error("Cannot update a patient without an original phone."); await api.put(`/patients/${encodeURIComponent(phone)}`, payload); }
      else await api.post("/patients", payload);
      toast.success(editingPatient ? "Patient updated" : "Patient saved"); setForm(emptyForm); setMedicineSearch(""); setEditingPatient(null); loadPatients(); loadAlerts();
    } catch (err) { toast.error(formatApiError(err)); }
  };
  const deletePatient = async (phone) => { const value = String(phone || "").trim(); if (!window.confirm(value ? "Delete patient?" : "Delete blank patient rows?")) return; try { await api.delete(value ? `/patients/${encodeURIComponent(value)}` : "/patients"); setPatients((rows) => rows.filter((p) => String(p.phone || "").trim() !== value)); setAlerts((rows) => rows.filter((p) => String(p.phone || "").trim() !== value)); toast.success("Patient deleted"); } catch (err) { toast.error(formatApiError(err)); } };
  const markContacted = async (phone) => { try { await api.post(`/patients/contacted/${phone}`); setAlerts((rows) => rows.filter((p) => p.phone !== phone)); } catch (err) { toast.error(formatApiError(err)); } };

  const matches = useMemo(() => { const q = medicineSearch.trim().toLowerCase(); if (!q) return medicines.slice(0, 8); return medicines.filter((m) => [medicineName(m), m.manufacturer, ...medicineBatches(m).map((b) => b.batch_no || b.batch_number)].some((v) => String(v || "").toLowerCase().includes(q))).slice(0, 8); }, [medicines, medicineSearch]);
  const linkedLowStock = useMemo(() => medicines.filter(isLowStock).map((medicine) => ({ medicine, patients: patients.filter((p) => String(p.medicine_name || "").trim().toLowerCase() === medicineName(medicine).trim().toLowerCase()) })).filter((row) => row.patients.length), [medicines, patients]);

  return <div className="space-y-6">
    <header className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-950">Patients</h1><p className="mt-1 text-sm text-slate-500">Simple refill and continuity tracking for your pharmacy.</p></div><div className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700"><CheckCircle2 className="h-4 w-4" /> Stock-safe patient records</div></header>

    {(alerts.length > 0 || linkedLowStock.length > 0) && <section className="rounded-xl border border-amber-200 bg-amber-50/70 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-amber-900"><AlertTriangle className="h-4 w-4" /> Refill attention</div><div className="grid gap-2 md:grid-cols-2">
      {linkedLowStock.map(({ medicine, patients: linked }) => <div key={medicine.id || medicineName(medicine)} className="rounded-lg border border-amber-200 bg-white px-3 py-2 text-sm"><span className="font-semibold text-slate-800">{linked.length} patient{linked.length === 1 ? "" : "s"} linked to low-stock {medicineName(medicine)}</span><span className="mt-0.5 block text-xs text-amber-700">Patient refill medicine {stockOf(medicine) <= 0 ? "unavailable" : `has ${stockOf(medicine)} units available`}.</span></div>)}
      {alerts.map((p, i) => <div key={p.phone || i} className="flex items-center justify-between gap-3 rounded-lg border border-amber-200 bg-white px-3 py-2"><div className="min-w-0 text-sm"><span className="block truncate font-semibold text-slate-800">{p.name} · {p.medicine_name}</span><span className="text-xs text-amber-700">Refill due — follow up with patient</span></div><button onClick={() => markContacted(p.phone)} className="shrink-0 text-xs font-semibold text-blue-700">Mark contacted</button></div>)}
    </div></section>}

    <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4"><h2 className="font-bold text-slate-900">{editingPatient ? "Edit patient" : "Add patient"}</h2><p className="text-xs text-slate-500">Only the essentials needed for pharmacy follow-ups.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      {[['name','Patient name *','text'],['phone','Phone *','tel'],['age','Age','number'],['address','Address','text'],['condition','Condition / note','text'],['duration_days','Refill duration (days)','number'],['last_refill_date','Last refill date','date']].map(([key,label,type]) => <label key={key} className={key === 'address' ? 'sm:col-span-2' : ''}><span className="mb-1 block text-xs font-semibold text-slate-600">{label}</span><input type={type} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>)}
      <label className="relative sm:col-span-2"><span className="mb-1 block text-xs font-semibold text-slate-600">Medicine from inventory</span><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={medicineSearch} onFocus={() => setShowMedicineResults(true)} onChange={(e) => { setMedicineSearch(e.target.value); setForm({ ...form, medicine_name: e.target.value }); setShowMedicineResults(true); }} placeholder="Search medicine name or batch…" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div>
      {showMedicineResults && medicineSearch && <div className="absolute z-20 mt-1 max-h-64 w-full overflow-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{matches.map((m) => { const batch = medicineBatches(m)[0] || {}; return <button type="button" key={m.id || medicineName(m)} onClick={() => { setForm({ ...form, medicine_name: medicineName(m) }); setMedicineSearch(medicineName(m)); setShowMedicineResults(false); }} className="flex w-full items-start justify-between gap-3 rounded-lg px-3 py-2 text-left hover:bg-slate-50"><span><strong className="block text-sm text-slate-900">{medicineName(m)}</strong><span className="text-xs text-slate-500">{batch.batch_no || batch.batch_number ? `Batch ${batch.batch_no || batch.batch_number}` : "Inventory item"}{batch.expiry_date ? ` · Exp ${batch.expiry_date}` : ""}</span></span><span className="shrink-0 text-right text-xs text-slate-500">{batch.mrp || m.mrp ? fmtINR(batch.mrp || m.mrp) : ""}<b className={`block ${isLowStock(m) ? "text-amber-700" : "text-emerald-700"}`}>{stockOf(m)} in stock</b></span></button>})}{!matches.length && <p className="p-3 text-sm text-slate-500">No inventory medicines found.</p>}</div>}</label>
    </div><div className="mt-4 rounded-lg border border-blue-100 bg-blue-50 px-3 py-2 text-xs leading-5 text-blue-800"><strong>Tracking only:</strong> Patient medicines are used for refill and continuity tracking only. Inventory changes happen through Billing.</div><div className="mt-4 flex gap-2"><button onClick={savePatient} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">{editingPatient ? "Update patient" : "Save patient"}</button>{editingPatient && <button onClick={() => { setEditingPatient(null); setForm(emptyForm); setMedicineSearch(""); }} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600">Cancel</button>}</div></section>

    <section><div className="mb-3 flex items-center justify-between"><h2 className="font-bold text-slate-900">Patient refill list</h2><span className="text-xs text-slate-500">{patients.length} patient{patients.length === 1 ? "" : "s"}</span></div><div className="grid gap-3 lg:grid-cols-2">{patients.map((p, i) => <article key={p.phone || i} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><UserRound className="h-4 w-4 text-slate-400"/><h3 className="truncate font-bold text-slate-900">{p.name || "Unnamed patient"}</h3>{p.is_due && <span className="rounded-full bg-red-50 px-2 py-0.5 text-[10px] font-bold uppercase text-red-700">Refill due</span>}</div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span className="flex items-center gap-1"><Phone className="h-3.5 w-3.5"/>{p.phone || "No phone"}</span>{p.doctor_name && <span>Doctor: {p.doctor_name}</span>}{p.condition && <span>{p.condition}</span>}</div></div><div className="flex gap-1"><button aria-label="Edit patient" onClick={() => selectForEdit(p)} className="rounded-lg p-2 text-blue-700 hover:bg-blue-50"><Edit3 className="h-4 w-4"/></button><button aria-label="Delete patient" onClick={() => deletePatient(p.phone)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></div></div><div className="mt-4 rounded-lg border border-slate-100 bg-slate-50 p-3"><div className="flex items-start gap-2"><PackageSearch className="mt-0.5 h-4 w-4 text-blue-600"/><div className="min-w-0"><div className="font-semibold text-slate-800">{p.medicine_name || "No refill medicine linked"}</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-500">{p.dosage && <span>Dosage: {p.dosage}</span>}{p.frequency && <span>Frequency: {p.frequency}</span>}{p.duration_days > 0 && <span>{p.duration_days}-day refill cycle</span>}{p.last_refill_date && <span className="flex items-center gap-1"><CalendarClock className="h-3.5 w-3.5"/>Last refill {p.last_refill_date}</span>}</div></div></div></div></article>)}{!patients.length && <div className="col-span-full rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No patients yet. Add a patient to start refill tracking.</div>}</div></section>
  </div>;
}
