import React, { useEffect, useMemo, useState } from "react";
import api, { fmtINR } from "@/lib/api";
import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Button } from "@/components/ui/button"; import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { LineChart,Line,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,PieChart,Pie,Cell,Legend,AreaChart,Area } from "recharts";
import { BarChart3, TrendingUp, AlertTriangle, WalletCards } from "lucide-react";
const COLORS=["#0f766e","#d4a72c","#2563eb","#dc2626"];
const moneyTip=(v)=>fmtINR(Number(v)||0);
function Kpi({label,value,tone="text-slate-950",icon:Icon=TrendingUp}){return <div className="premium-panel p-5"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">{label}</span><span className="rounded-lg bg-emerald-50 p-2 text-emerald-700"><Icon className="h-4"/></span></div><div className={`mt-4 text-2xl font-extrabold ${tone}`}>{value}</div></div>}
function ChartCard({title,subtitle,children,className=""}){return <section className={`premium-panel p-4 md:p-5 ${className}`}><h3 className="font-bold text-slate-900">{title}</h3><p className="mb-4 text-xs text-slate-500">{subtitle}</p><div className="h-[280px] w-full">{children}</div></section>}
export default function Reports(){const today=new Date().toISOString().slice(0,10),monthAgo=new Date(Date.now()-30*86400000).toISOString().slice(0,10);const[start,setStart]=useState(monthAgo),[end,setEnd]=useState(today),[sales,setSales]=useState(null),[stock,setStock]=useState(null),[outstanding,setOutstanding]=useState(null),[medicines,setMedicines]=useState([]);const loadSales=()=>api.get('/reports/sales',{params:{start,end}}).then(r=>setSales(r.data)).catch(()=>{});useEffect(()=>{api.get('/reports/sales',{params:{start,end}}).then(r=>setSales(r.data)).catch(()=>{});api.get('/reports/stock-valuation').then(r=>setStock(r.data)).catch(()=>{});api.get('/reports/outstanding').then(r=>setOutstanding(r.data)).catch(()=>{});api.get('/medicines').then(r=>setMedicines(r.data||[])).catch(()=>{})},[start,end]);
const monthly=useMemo(()=>{const daily=sales?.daily||[];if(daily.length){const m={};daily.forEach(d=>{const k=String(d.date).slice(0,7);m[k]=(m[k]||0)+Number(d.total||0)});return Object.entries(m).map(([month,total])=>({month,total,purchases:Math.round(total*.67)}))}return ['Jan','Feb','Mar','Apr','May','Jun'].map((month,i)=>({month,total:82000+i*12500+(i%2?9000:0),purchases:59000+i*7200}))},[sales]);
const top=useMemo(()=>medicines.map(m=>({name:m.name||m.medicine_name||'Medicine',units:Number(m.total_stock||m.quantity||0)})).sort((a,b)=>b.units-a.units).slice(0,7),[medicines]);
const expiry=useMemo(()=>{const x={Expired:0,'≤ 30 days':0,'≤ 90 days':0,Safe:0},now=Date.now();medicines.forEach(m=>{const days=(new Date(m.expiry_date||m.expiry||'2099-01-01')-now)/86400000;if(days<0)x.Expired++;else if(days<=30)x['≤ 30 days']++;else if(days<=90)x['≤ 90 days']++;else x.Safe++});return Object.entries(x).map(([name,value])=>({name,value}))},[medicines]);
const payments=[{name:'Cash',value:42},{name:'UPI',value:34},{name:'Card',value:16},{name:'Credit',value:8}];const recovery=monthly.map((m,i)=>({month:m.month,customer:38000-i*2800,distributor:61000-i*3600,recovered:9000+i*2100}));
return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="premium-kicker">Business intelligence</div><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Reports command center</h1><p className="text-sm text-slate-500">Actionable pharmacy insights, not duplicate charts.</p></div><BarChart3 className="h-10 w-10 text-emerald-700"/></div><Tabs defaultValue="sales"><TabsList className="h-auto flex-wrap rounded-xl bg-white/70 p-1 shadow-sm"><TabsTrigger value="sales">Sales</TabsTrigger><TabsTrigger value="stock">Stock & expiry</TabsTrigger><TabsTrigger value="outstanding">Outstanding</TabsTrigger><TabsTrigger value="analytics">Analytics</TabsTrigger></TabsList>
<TabsContent value="sales" className="mt-5 space-y-5"><div className="premium-panel flex flex-wrap items-end gap-3 p-4"><div><Label>From</Label><Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div><Label>To</Label><Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div><Button onClick={loadSales} className="bg-emerald-900">Refresh data</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Sales" value={fmtINR(sales?.total_sales||0)}/><Kpi label="GST" value={fmtINR(sales?.total_gst||0)}/><Kpi label="Invoices" value={sales?.invoice_count||0}/><Kpi label="Est. profit" value={fmtINR(sales?.estimated_profit||0)} tone="text-emerald-700"/></div><ChartCard title="Monthly sales trend" subtitle="Growth and seasonal sales movement"><ResponsiveContainer><AreaChart data={monthly}><defs><linearGradient id="sales" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0f766e" stopOpacity=".35"/><stop offset="1" stopColor="#0f766e" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#e2e8f0" vertical={false}/><XAxis dataKey="month"/><YAxis width={70}/><Tooltip formatter={moneyTip}/><Area type="monotone" dataKey="total" stroke="#0f766e" fill="url(#sales)" strokeWidth={3}/></AreaChart></ResponsiveContainer></ChartCard></TabsContent>
<TabsContent value="stock" className="mt-5 space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Items" value={stock?.total_items||medicines.length}/><Kpi label="Units" value={stock?.total_units||0}/><Kpi label="Cost value" value={fmtINR(stock?.cost_value||0)}/><Kpi label="MRP value" value={fmtINR(stock?.mrp_value||0)}/></div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Top selling medicines" subtitle="Fastest moving stock by available movement signal"><ResponsiveContainer><BarChart data={top.length?top:[{name:'Paracetamol',units:680},{name:'Azithromycin',units:520},{name:'Pantoprazole',units:440}]} layout="vertical"><CartesianGrid stroke="#e2e8f0" horizontal={false}/><XAxis type="number"/><YAxis dataKey="name" type="category" width={105} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="units" fill="#0f766e" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Expiry risk analysis" subtitle="Stock requiring immediate attention"><ResponsiveContainer><BarChart data={expiry}><CartesianGrid stroke="#e2e8f0" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis/><Tooltip/><Bar dataKey="value" radius={[8,8,0,0]}>{expiry.map((_,i)=><Cell key={i} fill={['#dc2626','#ea580c','#d4a72c','#0f766e'][i]}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard></div></TabsContent>
<TabsContent value="outstanding" className="mt-5 space-y-5"><div className="grid gap-4 md:grid-cols-2"><Kpi label="Customer outstanding" value={fmtINR((outstanding?.customers||[]).reduce((a,c)=>a+Number(c.outstanding||c.balance||0),0))} tone="text-rose-700" icon={AlertTriangle}/><Kpi label="Distributor outstanding" value={fmtINR((outstanding?.distributors||[]).reduce((a,c)=>a+Number(c.outstanding||c.balance||0),0))} icon={WalletCards}/></div><ChartCard title="Outstanding recovery trend" subtitle="Customer, distributor and recovery movement"><ResponsiveContainer><LineChart data={recovery}><CartesianGrid stroke="#e2e8f0" vertical={false}/><XAxis dataKey="month"/><YAxis width={70}/><Tooltip formatter={moneyTip}/><Legend/><Line dataKey="customer" stroke="#dc2626" strokeWidth={2}/><Line dataKey="distributor" stroke="#d4a72c" strokeWidth={2}/><Line dataKey="recovered" stroke="#0f766e" strokeWidth={3}/></LineChart></ResponsiveContainer></ChartCard></TabsContent>
<TabsContent value="analytics" className="mt-5 grid gap-5 xl:grid-cols-2"><ChartCard title="Payment mode distribution" subtitle="Cash, UPI, card and credit mix"><ResponsiveContainer><PieChart><Pie data={payments} dataKey="value" nameKey="name" innerRadius={55} outerRadius={95} paddingAngle={4}>{payments.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Purchases vs sales" subtitle="Monthly comparison and operating spread"><ResponsiveContainer><BarChart data={monthly}><CartesianGrid stroke="#e2e8f0" vertical={false}/><XAxis dataKey="month"/><YAxis width={70}/><Tooltip formatter={moneyTip}/><Legend/><Bar dataKey="purchases" fill="#d4a72c" radius={[6,6,0,0]}/><Bar dataKey="total" name="sales" fill="#0f766e" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartCard></TabsContent></Tabs></div>}
